# 1단계: 빌드 스테이지
FROM node:20-slim AS builder

WORKDIR /usr/src/app

# 빌드 인자 정의
ARG DATABASE_CLIENT
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_SCHEMA
ARG DATABASE_PORT
ARG DATABASE_SSL
ARG DATABASE_USERNAME
ARG FIREBASE_STORAGE_BUCKET
ARG GENERATE_SOURCEMAP
ARG HOST
ARG PORT
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USERNAME
ARG URL
ARG DATABASE_PASSWORD
ARG DATABASE_SSL_CA_CONTENT
ARG JWT_SECRET
ARG ADMIN_JWT_SECRET
ARG APP_KEYS
ARG API_TOKEN_SALT
ARG TRANSFER_TOKEN_SALT
ARG SMTP_PASSWORD
ARG FIREBASE_SERVICE_ACCOUNT

# 환경 변수 설정
ENV DATABASE_CLIENT=$DATABASE_CLIENT \
    DATABASE_HOST=$DATABASE_HOST \
    DATABASE_NAME=$DATABASE_NAME \
    DATABASE_SCHEMA=$DATABASE_SCHEMA \
    DATABASE_PORT=$DATABASE_PORT \
    DATABASE_SSL=$DATABASE_SSL \
    DATABASE_USERNAME=$DATABASE_USERNAME \
    FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET \
    GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP \
    HOST=$HOST \
    PORT=$PORT \
    SMTP_HOST=$SMTP_HOST \
    SMTP_PORT=$SMTP_PORT \
    SMTP_USERNAME=$SMTP_USERNAME \
    URL=$URL

# 인증서 디렉토리 생성 (빌드 시 필요할 경우 대비)
RUN mkdir -p /etc/ssl/aiven && \
    echo "$DATABASE_SSL_CA_CONTENT" | base64 -d > /etc/ssl/aiven/ca.pem

COPY package*.json ./
RUN npm ci

COPY . .
RUN rm -rf .cache && \
    DATABASE_PASSWORD=$DATABASE_PASSWORD \
    DATABASE_SSL_CA_CONTENT=$DATABASE_SSL_CA_CONTENT \
    JWT_SECRET=$JWT_SECRET \
    ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET \
    APP_KEYS=$APP_KEYS \
    API_TOKEN_SALT=$API_TOKEN_SALT \
    TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT \
    SMTP_PASSWORD=$SMTP_PASSWORD \
    FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT \
    npm run build

# 2단계: 실행 스테이지 (경량화)
FROM node:20-slim

WORKDIR /usr/src/app

# 빌드 결과물 및 필수 파일 복사
COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/public ./public
# 인증서 파일 포함
COPY --from=builder /etc/ssl/aiven/ca.pem /etc/ssl/aiven/ca.pem

# 프로덕션 의존성만 설치
RUN npm ci --only=production

# 환경 변수 재설정 (실행 시 필요)
ENV NODE_ENV=production

EXPOSE 1337
CMD ["npm", "run", "start"]
