# Stage 1: Build
FROM node:20 AS build

WORKDIR /usr/src/app

# Normal 변수
ARG DATABASE_CLIENT
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_PORT
ARG DATABASE_SSL
ARG DATABASE_USERNAME
ARG FIREBASE_STORAGE_BUCKET
ARG GENERATE_SOURCEMAP
ARG HOST
ARG PORT
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USERNAME
ARG URL

# Secrets 변수
ARG ADMIN_JWT_SECRET
ARG API_TOKEN_SALT
ARG APP_KEYS
ARG DATABASE_PASSWORD
ARG FIREBASE_SERVICE_ACCOUNT
ARG JWT_SECRET
ARG SMTP_PASSWORD
ARG TRANSFER_TOKEN_SALT

# ARG → ENV 전환
ENV DATABASE_CLIENT=$DATABASE_CLIENT \
    DATABASE_HOST=$DATABASE_HOST \
    DATABASE_NAME=$DATABASE_NAME \
    DATABASE_PORT=$DATABASE_PORT \
    DATABASE_SSL=$DATABASE_SSL \
    DATABASE_USERNAME=$DATABASE_USERNAME \
    DATABASE_PASSWORD=$DATABASE_PASSWORD \
    FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET \
    FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT \
    GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP \
    HOST=$HOST \
    PORT=$PORT \
    SMTP_HOST=$SMTP_HOST \
    SMTP_PORT=$SMTP_PORT \
    SMTP_USERNAME=$SMTP_USERNAME \
    SMTP_PASSWORD=$SMTP_PASSWORD \
    JWT_SECRET=$JWT_SECRET \
    ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET \
    APP_KEYS=$APP_KEYS \
    API_TOKEN_SALT=$API_TOKEN_SALT \
    TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT \
    URL=$URL

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Production
FROM node:20

WORKDIR /usr/src/app

COPY --from=build /usr/src/app ./

ARG DATABASE_CLIENT
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_PORT
ARG DATABASE_SSL
ARG DATABASE_USERNAME
ARG DATABASE_PASSWORD
ARG FIREBASE_STORAGE_BUCKET
ARG FIREBASE_SERVICE_ACCOUNT
ARG GENERATE_SOURCEMAP
ARG HOST
ARG PORT
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USERNAME
ARG SMTP_PASSWORD
ARG JWT_SECRET
ARG ADMIN_JWT_SECRET
ARG APP_KEYS
ARG API_TOKEN_SALT
ARG TRANSFER_TOKEN_SALT
ARG URL

ENV DATABASE_CLIENT=$DATABASE_CLIENT \
    DATABASE_HOST=$DATABASE_HOST \
    DATABASE_NAME=$DATABASE_NAME \
    DATABASE_PORT=$DATABASE_PORT \
    DATABASE_SSL=$DATABASE_SSL \
    DATABASE_USERNAME=$DATABASE_USERNAME \
    DATABASE_PASSWORD=$DATABASE_PASSWORD \
    FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET \
    FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT \
    GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP \
    HOST=$HOST \
    PORT=$PORT \
    SMTP_HOST=$SMTP_HOST \
    SMTP_PORT=$SMTP_PORT \
    SMTP_USERNAME=$SMTP_USERNAME \
    SMTP_PASSWORD=$SMTP_PASSWORD \
    JWT_SECRET=$JWT_SECRET \
    ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET \
    APP_KEYS=$APP_KEYS \
    API_TOKEN_SALT=$API_TOKEN_SALT \
    TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT \
    URL=$URL

EXPOSE 1337
CMD ["npm", "run", "start"]