FROM node:20-slim

WORKDIR /usr/src/app

# 비민감 빌드 변수 (ENV로 이미지에 고정)
ARG DATABASE_CLIENT
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_SCHEMA
ARG DATABASE_PORT
ARG DATABASE_SSL
ARG DATABASE_USERNAME
ARG FIREBASE_STORAGE_BUCKET
ARG GENERATE_SOURCEMAP
ARG HOST
ARG PORT
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USERNAME
ARG URL

ENV DATABASE_CLIENT=$DATABASE_CLIENT \
    DATABASE_HOST=$DATABASE_HOST \
    DATABASE_NAME=$DATABASE_NAME \
    DATABASE_SCHEMA=$DATABASE_SCHEMA \
    DATABASE_PORT=$DATABASE_PORT \
    DATABASE_SSL=$DATABASE_SSL \
    DATABASE_USERNAME=$DATABASE_USERNAME \
    FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET \
    GENERATE_SOURCEMAP=$GENERATE_SOURCEMAP \
    HOST=$HOST \
    PORT=$PORT \
    SMTP_HOST=$SMTP_HOST \
    SMTP_PORT=$SMTP_PORT \
    SMTP_USERNAME=$SMTP_USERNAME \
    URL=$URL

# 민감 빌드 변수 (빌드 시에만 임시 사용)
ARG DATABASE_PASSWORD
ARG JWT_SECRET
ARG ADMIN_JWT_SECRET
ARG APP_KEYS
ARG API_TOKEN_SALT
ARG TRANSFER_TOKEN_SALT
ARG SMTP_PASSWORD
ARG FIREBASE_SERVICE_ACCOUNT

COPY package*.json ./
RUN npm ci --only=production

COPY . .

# 민감 변수는 빌드 시에만 임시 주입
RUN DATABASE_PASSWORD=$DATABASE_PASSWORD \
    JWT_SECRET=$JWT_SECRET \
    ADMIN_JWT_SECRET=$ADMIN_JWT_SECRET \
    APP_KEYS=$APP_KEYS \
    API_TOKEN_SALT=$API_TOKEN_SALT \
    TRANSFER_TOKEN_SALT=$TRANSFER_TOKEN_SALT \
    SMTP_PASSWORD=$SMTP_PASSWORD \
    FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT \
    npm run build

EXPOSE 1337
CMD ["npm", "run", "start"]
